const charlas = [
    { id:"01", categoria:"Programación", title:"React", speaker:"Juan", descripcion:"React es una biblioteca Javascript de código abierto diseñada para crear interfaces de usuario con el objetivo de facilitar el desarrollo de aplicaciones en una sola página.", price: 5000, pictureUrl:"../../assets/react.png", stock:10},
    { id:"02", categoria:"Programación", title:"Java", speaker:"Pedro", descripcion:"Java es rápido, seguro y fiable. Desde ordenadores portátiles hasta centros de datos, desde consolas para juegos hasta computadoras avanzadas, desde teléfonos móviles hasta Internet, Java está en todas partes. ", price: 5000, pictureUrl:"../../assets/java.png", stock:"20"},
    { id:"03", categoria:"Programación", title:"Vue", speaker:"Juan", descripcion:"Vue.js es un framework de JavaScript de código abierto para la construcción de interfaces de usuario y aplicaciones de una sola página.", price: 5000, pictureUrl:"../../assets/vue.png", stock:10},
    { id:"04", categoria:"Programación", title:"JavaScript", speaker:"Pedro",  descripcion:"JavaScript es un lenguaje de programación interpretado, dialecto del estándar ECMAScript. Se define como orientado a objetos, ​ basado en prototipos, imperativo, débilmente tipado y dinámico.", price: 14000, pictureUrl:"../../assets/js.png", stock:30},
    { id:"05", categoria:"Programación", title:"Html", speaker:"Juan", descripcion:"HTML, siglas en inglés de HyperText Markup Language, hace referencia al lenguaje de marcado para la elaboración de páginas web", price: 3000, pictureUrl:"../../assets/html.png", stock:10},
    { id:"06", categoria:"Programación", title:"CSS", speaker:"Pedro", descripcion:"CSS, en español «Hojas de estilo en cascada», es un lenguaje de diseño gráfico para definir y crear la presentación de un documento estructurado escrito en un lenguaje de marcado.", price: 4000, pictureUrl:"../../assets/css.png", stock:5},
    { id:"07", categoria:"Edición", title:"Adobe Premiere", speaker:"Juan", descripcion:"Adobe Premiere Pro es un software de edición de video desarrollado por Adobe y publicado como parte de Adobe Creative Cloud. Está orientado a la edición de vídeos profesionales.", price: 10000, pictureUrl:"../../assets/premiere.png", stock:15},
    { id:"08", categoria:"Edición", title:"Adobe After Effects", speaker:"Pedro", descripcion:"Adobe After Effects es una aplicación que tiene forma de estudio destinado para la creación o aplicación en una composición, así como realización de gráficos profesionales en movimiento y efectos especiales, que desde sus raíces han consistido básicamente en la superposición de capas.",  price:12000, pictureUrl:"../../assets/after-effects.png", stock:20},
    { id:"09", categoria:"Edición", title:"Adobe Audition", speaker:"Juan", descripcion:"Adobe Audition (anteriormente Cool Edit Pro) es una aplicación en forma de estudio de sonido destinado a la edición de audio digital de Adobe Systems Incorporated que permite tanto un entorno de edición mezclado de ondas multipista no-destructivo como uno destructivo, por lo que se le ha llamado la ´navaja suiza´ del audio digital por su versatilidad.", price:8000, pictureUrl:"../../assets/audition.png", stock:10},
    { id:"10", categoria:"Edición", title:"Adobe Photoshop ", speaker:"Pedro", descripcion:"Adobe Photoshop es un editor de fotografías desarrollado por Adobe Systems Incorporated. Usado principalmente para el retoque de fotografías y gráficos, su nombre en español significa ´taller de fotos´. Es conocido mundialmente.​", price:5000, pictureUrl:"../../assets/adobe-photoshop.png", stock:20},
    { id:"11", categoria:"Edición", title:"Adobe Illustrador", speaker:"Juan", descripcion:"Adobe Illustrator es un editor de gráficos vectoriales sirve para editar entre otras cosas. Es desarrollado y comercializado por Adobe Systems y constituye su primer programa oficial de su tipo en ser lanzado por esta compañía definiendo en cierta manera el lenguaje gráfico contemporáneo mediante el dibujo vectorial.",  price:5000, pictureUrl:"../../assets/adobe-illustrator.png", stock:10},
];

const GetFetchList = new Promise ((resolve, reject) => {
    setTimeout(() => {
        resolve(charlas);
    }, 1000);
})

export default GetFetchList